apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkedeye-itsm-ingress
  namespace: linkedeye-core
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/websocket-services: linkedeye-api
spec:
  ingressClassName: nginx
  rules:
    - host: itsm.wecrew.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: linkedeye-api
                port:
                  number: 5000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: linkedeye-api
                port:
                  number: 5000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: linkedeye-api
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkedeye-frontend
                port:
                  number: 80
