apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkedeye-core

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: linkedeye-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"

images:
  - name: linkedeye/api
    newTag: "2.0.0"
  - name: linkedeye/frontend
    newTag: "2.0.0"
