apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkedeye-uploads
  labels:
    app.kubernetes.io/name: linkedeye-uploads
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: linkedeye
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
